name: Flat Share Client CI/CD 

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm" 

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.FLATSHARE_CLIENT_VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.FLATSHARE_CLIENT_ORG_ID }}
          vercel-project-id: ${{ secrets.FLATSHARE_CLIENT_PROJECT_ID }}
          vercel-args: "--prod"

